server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    password: 101673
    username: root
    url: jdbc:mysql://localhost:3306/myjwtauth?characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      password: 101673
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: del_flag
